

spring.application.name=apiValidation

# --- CONFIGURAÇÕES DE CONEXÃO (DATASOURCE) ---

# Define onde o banco está. 'mem:testdb' significa que o banco rodará na MEMÓRIA RAM (é volátil)
spring.datasource.url=jdbc:h2:mem:testdb

# O driver específico que o Java usa para conversar com o H2
spring.datasource.driverClassName=org.h2.Driver

# Usuário padrão do H2 (sa = System Administrator)
spring.datasource.username=sa

# Senha padrão (em branco)
spring.datasource.password=

# --- CONFIGURAÇÕES DO JPA / HIBERNATE ---
# Diz ao Hibernate para usar a "gramática" (dialeto) específica do H2 ao gerar SQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# A MÁGICA: 'update' faz o Hibernate criar ou alterar as tabelas no banco
# automaticamente baseando-se nas suas classes Java (@Entity)
spring.jpa.hibernate.ddl-auto=update

# --- CONFIGURAÇÕES DO CONSOLE VISUAL ---
# Habilita uma interface gráfica no navegador para você ver o banco de dados
spring.h2.console.enabled=true

# O endereço para acessar o console (ex: localhost:8080/h2-console)
spring.h2.console.path=/h2-console